export const CSS = `
  *{box-sizing:border-box;-webkit-tap-highlight-color:transparent;}
  body{margin:0;background:#ede8e0;}
  .pg{padding-bottom:16px;}
  .fade{animation:fi .25s ease;}
  .no-scroll::-webkit-scrollbar{display:none;}
  .no-scroll{-ms-overflow-style:none;scrollbar-width:none;}
  @keyframes fi{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:none}}
  input,textarea,select{-webkit-appearance:none;appearance:none;}
  button{transition:opacity .15s,transform .1s;}
  button:active{transform:scale(.96);opacity:.85;}
  a:active{opacity:.8;}
`;

export const S = {
  root:      { minHeight:"100vh", paddingBottom:64, maxWidth:430, margin:"0 auto", boxShadow:"0 0 60px rgba(0,0,0,.12)" },
  body:      { paddingTop:62 },
  toast:     { position:"fixed", top:68, left:"50%", transform:"translateX(-50%)", color:"#fff", padding:"10px 22px", borderRadius:30, zIndex:9999, fontSize:14, fontWeight:700, boxShadow:"0 4px 20px rgba(0,0,0,.2)", whiteSpace:"nowrap" },
  nav:       { position:"fixed", top:0, left:"50%", transform:"translateX(-50%)", width:"100%", maxWidth:430, zIndex:100, backdropFilter:"blur(16px)", borderBottom:"1px solid", height:62, display:"flex", alignItems:"center", justifyContent:"space-between", padding:"0 18px", boxSizing:"border-box" },
  navLogo:   { background:"none", border:"none", cursor:"pointer", padding:0, textAlign:"left" },
  navName:   { display:"block", fontSize:18, fontWeight:700, fontStyle:"italic" },
  navRole:   { display:"block", fontSize:9, letterSpacing:2.5, textTransform:"uppercase", marginTop:-1 },
  navAdminBtn:{ background:"none", border:"none", cursor:"pointer", fontSize:22, padding:8 },
  bar:       { position:"fixed", bottom:0, left:"50%", transform:"translateX(-50%)", width:"100%", maxWidth:430, backdropFilter:"blur(14px)", borderTop:"1px solid", display:"flex", zIndex:100, boxSizing:"border-box" },
  barBtn:    { flex:1, display:"flex", flexDirection:"column", alignItems:"center", gap:1, background:"none", border:"none", cursor:"pointer", padding:"8px 4px 10px", position:"relative" },
  barIc:     { fontSize:19 },
  barDot:    { position:"absolute", bottom:4, width:4, height:4, borderRadius:"50%" },
  hero:      { height:420, display:"flex", alignItems:"flex-end", overflow:"hidden", position:"relative" },
  heroContent:{ padding:"0 22px 32px", width:"100%", position:"relative", zIndex:1 },
  heroTag:   { display:"inline-block", fontSize:10, padding:"5px 14px", borderRadius:20, letterSpacing:2.5, textTransform:"uppercase", marginBottom:10, color:"rgba(255,255,255,.9)", border:"1px solid" },
  heroH1:    { fontFamily:"Georgia,serif", fontSize:54, fontWeight:700, color:"#fff", margin:"0 0 4px", lineHeight:.9 },
  heroScript:{ fontStyle:"italic", fontWeight:300 },
  heroQ:     { color:"rgba(255,255,255,.75)", fontStyle:"italic", fontFamily:"Georgia,serif", fontSize:14, margin:"6px 0 18px" },
  heroBtnO:  { background:"rgba(255,255,255,.15)", color:"#fff", border:"1.5px solid rgba(255,255,255,.4)", padding:"12px 22px", borderRadius:40, fontSize:13, fontWeight:600, cursor:"pointer", backdropFilter:"blur(8px)" },
  feats:     { display:"flex", gap:10, padding:"14px 16px 4px" },
  feat:      { flex:1, borderRadius:14, padding:"14px 10px", textAlign:"center", display:"flex", flexDirection:"column", gap:4, alignItems:"center" },
  featT:     { margin:0, fontSize:12, fontWeight:700 },
  featD:     { margin:0, fontSize:10.5, color:"#9a7060", lineHeight:1.4 },
  section:   { padding:"14px 16px 4px" },
  sHead:     { display:"flex", justifyContent:"space-between", alignItems:"center", marginBottom:10 },
  sTitle:    { margin:0, fontSize:18, fontStyle:"italic" },
  sMore:     { background:"none", border:"none", cursor:"pointer", fontSize:13, fontWeight:700 },
  hScroll:   { display:"flex", gap:10, overflowX:"auto", paddingBottom:8 },
  hCard:     { flex:"0 0 140px", background:"#fff", borderRadius:14, overflow:"hidden", border:"1px solid", borderTop:"3px solid" },
  hCardImg:  { width:"100%", height:100, objectFit:"cover", display:"block" },
  hCardBody: { padding:"9px 10px 12px" },
  hCardCat:  { margin:"0 0 1px", fontSize:9.5, textTransform:"uppercase", letterSpacing:1 },
  hCardName: { margin:"0 0 4px", fontSize:12.5, fontWeight:700, lineHeight:1.3 },
  hCardPrice:{ margin:0, fontSize:14, fontWeight:700 },
  ctaStrip:  { margin:"20px 16px", borderRadius:18, padding:"24px 20px", textAlign:"center" },
  ctaT:      { fontFamily:"Georgia,serif", fontSize:18, color:"#fff", margin:"0 0 6px", fontStyle:"italic" },
  ctaS:      { color:"rgba(255,255,255,.55)", fontSize:13, margin:"0 0 16px" },
  progress:  { display:"flex", gap:0, padding:"14px 16px 2px", overflowX:"auto" },
  pItem:     { display:"flex", flexDirection:"column", alignItems:"center", gap:4, flex:1, minWidth:46, color:"#9a7060", fontSize:10 },
  pCirc:     { width:26, height:26, borderRadius:"50%", background:"#faf3ed", border:"2px solid #ecddd5", display:"flex", alignItems:"center", justifyContent:"center", fontSize:12, fontWeight:700, color:"#9a7060" },
  hint:      { padding:"10px 16px 2px", color:"#9a7060", fontSize:13, lineHeight:1.6 },
  datePill:  { background:"#faf3ed", border:"1px solid", borderRadius:20, padding:"5px 14px", fontSize:12.5, fontWeight:700 },
  cal:       { background:"#fff", borderRadius:18, border:"1px solid", padding:"14px", margin:"10px 0", boxShadow:"0 2px 12px rgba(0,0,0,.06)" },
  calHead:   { display:"flex", alignItems:"center", justifyContent:"space-between", marginBottom:12 },
  calNav:    { background:"#faf3ed", border:"1px solid", width:34, height:34, borderRadius:10, cursor:"pointer", fontSize:20, fontWeight:700, display:"flex", alignItems:"center", justifyContent:"center" },
  calMon:    { fontSize:16, fontStyle:"italic", fontWeight:700 },
  calGrid:   { display:"grid", gridTemplateColumns:"repeat(7,1fr)", gap:2 },
  calDow:    { textAlign:"center", fontSize:9.5, color:"#9a7060", fontWeight:700, paddingBottom:7, letterSpacing:.5 },
  calDay:    { aspectRatio:"1", display:"flex", alignItems:"center", justifyContent:"center", borderRadius:8, fontSize:12.5, color:"#ddd", cursor:"default", border:"1px solid transparent", position:"relative", background:"none" },
  calDot:    { position:"absolute", bottom:1, right:1, width:5, height:5, borderRadius:"50%" },
  calLeg:    { display:"flex", gap:10, marginTop:10, flexWrap:"wrap" },
  legI:      { display:"flex", alignItems:"center", gap:4, fontSize:10.5, color:"#9a7060" },
  legDot:    { width:9, height:9, borderRadius:"50%", display:"inline-block" },
  slotsGrid: { display:"flex", flexWrap:"wrap", gap:8, padding:"10px 0" },
  slotB:     { background:"#fff", border:"1.5px solid", color:"#3a2418", padding:"12px 18px", borderRadius:40, cursor:"pointer", fontSize:14, fontWeight:700 },
  slotChip:  { display:"flex", alignItems:"center", gap:2, background:"#faf3ed", border:"1px solid", padding:"7px 12px", borderRadius:20, fontSize:13, fontWeight:700 },
  catLbl:    { padding:"10px 0 4px", color:"#9a7060", fontSize:10.5, letterSpacing:2, textTransform:"uppercase", fontWeight:700, margin:0 },
  svcRow:    { display:"flex", alignItems:"center", gap:12, background:"#fff", border:"1px solid", borderRadius:14, padding:"13px 16px", marginBottom:8, cursor:"pointer", width:"100%", boxSizing:"border-box" },
  svcDot:    { width:10, height:10, borderRadius:"50%", flexShrink:0 },
  svcRN:     { margin:0, fontWeight:700, fontSize:14 },
  svcRD:     { margin:"2px 0 0", color:"#9a7060", fontSize:11.5 },
  svcRP:     { fontWeight:700, fontSize:16, flexShrink:0 },
  summCard:  { background:"#fff", border:"1px solid #ecddd5", borderRadius:14, padding:"13px 16px", margin:"10px 0" },
  summTitle: { fontSize:10.5, color:"#9a7060", letterSpacing:2, textTransform:"uppercase", margin:"0 0 8px", fontWeight:700 },
  doneRing:  { width:70, height:70, borderRadius:"50%", display:"flex", alignItems:"center", justifyContent:"center", fontSize:32, color:"#fff", boxShadow:"0 8px 24px rgba(0,0,0,.15)" },
  doneBox:   { background:"#fff", border:"1px solid #ecddd5", borderRadius:14, padding:"13px 16px" },
  dRow:      { display:"flex", justifyContent:"space-between", padding:"6px 0", borderBottom:"1px solid #f5ede6" },
  sCard:     { background:"#fff", border:"1px solid", borderLeft:"3px solid", borderRadius:14, padding:14, marginBottom:12 },
  sCardImg:  { width:80, height:80, objectFit:"cover", borderRadius:10, flexShrink:0 },
  sCardN:    { margin:"0 0 4px", fontWeight:700, fontSize:14 },
  sCardD:    { margin:"0 0 4px", color:"#9a7060", fontSize:12, lineHeight:1.5 },
  sCardDur:  { margin:0, color:"#9a7060", fontSize:12 },
  sCardP:    { fontWeight:700, fontSize:16, flexShrink:0 },
  chip:      { display:"inline-block", border:"1px solid", fontSize:10.5, padding:"3px 8px", borderRadius:20, marginBottom:2 },
  mdBg:      { position:"fixed", inset:0, background:"rgba(30,10,0,.55)", zIndex:500, display:"flex", alignItems:"flex-end", justifyContent:"center" },
  md:        { background:"#fff", borderRadius:"22px 22px 0 0", padding:"24px 20px 32px", width:"100%", maxWidth:430, maxHeight:"90vh", overflowY:"auto", position:"relative", boxShadow:"0 -12px 40px rgba(0,0,0,.2)" },
  mdX:       { position:"absolute", top:12, right:14, background:"#f5ede6", border:"none", borderRadius:"50%", width:30, height:30, fontSize:16, cursor:"pointer", color:"#9a7060", display:"flex", alignItems:"center", justifyContent:"center" },
  btnP:      { background:"#9b7adb", color:"#fff", border:"none", padding:"14px 24px", borderRadius:40, cursor:"pointer", fontWeight:700, fontSize:14, display:"block", textAlign:"center", width:"100%", boxSizing:"border-box" },
  btnOut:    { background:"transparent", border:"1.5px solid", padding:"13px 24px", borderRadius:40, cursor:"pointer", fontWeight:700, fontSize:14, display:"block", textAlign:"center", width:"100%", boxSizing:"border-box" },
  btnWa:     { background:"#25d366", color:"#fff", border:"none", padding:"13px 24px", borderRadius:40, cursor:"pointer", fontWeight:700, fontSize:14, textDecoration:"none", display:"inline-block", boxSizing:"border-box" },
  backBtn:   { background:"#faf3ed", border:"1px solid", color:"#9a7060", padding:"8px 14px", borderRadius:20, cursor:"pointer", fontSize:13 },
  empty:     { background:"#faf3ed", border:"1px solid #ecddd5", borderRadius:14, padding:"24px 16px", textAlign:"center", color:"#9a7060", fontSize:13, lineHeight:1.7 },
  catTabs:   { display:"flex", gap:8, padding:"14px 16px 4px" },
  catB:      { flex:1, background:"#fff", border:"1.5px solid", padding:"12px 0", borderRadius:40, cursor:"pointer", fontSize:13.5, width:"100%" },
  aboutHero: { display:"flex", flexDirection:"column", alignItems:"center", padding:"28px 20px 16px", textAlign:"center" },
  aboutAv:   { width:100, height:100, borderRadius:"50%", display:"flex", alignItems:"center", justifyContent:"center", fontSize:36, color:"rgba(255,255,255,.6)", marginBottom:12 },
  aboutName: { fontSize:26, margin:"0 0 2px", fontStyle:"italic" },
  aboutRole: { fontSize:12.5, letterSpacing:1.5, textTransform:"uppercase", margin:"0 0 12px" },
  aboutBio:  { color:"#9a7060", fontSize:14, lineHeight:1.7, maxWidth:340, margin:"0 0 18px" },
  instaCard: { display:"flex", gap:14, alignItems:"center", background:"linear-gradient(135deg,#fdf0fc,#f5e8ff)", border:"1px solid #e0c0f0", borderRadius:14, padding:"14px 16px", textDecoration:"none", marginBottom:10 },
  pillar:    { background:"#fff", border:"1px solid", borderRadius:14, padding:"13px 15px", marginBottom:10 },
  pillarT:   { margin:"0 0 2px", fontWeight:700, fontSize:13.5 },
  pillarD:   { margin:0, color:"#9a7060", fontSize:12.5, lineHeight:1.5 },
  payBox:    { background:"#fdf0e8", border:"1px solid", borderRadius:14, padding:"16px", textAlign:"center" },
  payTitle:  { fontSize:15, margin:"0 0 10px", fontStyle:"italic" },
  payChip:   { display:"inline-block", background:"#fff", border:"1px solid", borderRadius:20, padding:"7px 16px", fontSize:13, fontWeight:600, margin:"4px" },
  aTabBar:   { display:"flex", gap:0, overflowX:"auto", borderBottom:"1px solid", background:"#fff" },
  aTab:      { background:"none", border:"none", color:"#9a7060", padding:"13px 10px", fontSize:11.5, cursor:"pointer", whiteSpace:"nowrap", borderBottom:"2.5px solid transparent" },
  bk:        { background:"#fff", border:"1px solid", borderLeft:"3px solid #9b7adb", borderRadius:12, padding:"12px 14px", marginBottom:10 },
  bkName:    { margin:"0 0 3px", fontWeight:700, fontSize:14.5 },
  bkInfo:    { margin:"2px 0", color:"#9a7060", fontSize:12.5 },
  badge:     { padding:"4px 10px", borderRadius:20, fontSize:11, fontWeight:700, flexShrink:0 },
  aBtn:      { background:"#faf3ed", border:"1px solid", color:"#7a6060", padding:"7px 12px", borderRadius:20, cursor:"pointer", fontSize:12 },
  pill:      { background:"#faf3ed", border:"1px solid", color:"#7a6060", padding:"7px 13px", borderRadius:20, cursor:"pointer", fontSize:12.5 },
  kpiGrid:   { display:"grid", gridTemplateColumns:"1fr 1fr", gap:10 },
  kpi:       { background:"#fff", border:"1px solid", borderRadius:12, padding:"12px 14px" },
  card_:     { background:"#fff", border:"1px solid", borderRadius:14, padding:"16px" },
  lbl:       { display:"flex", flexDirection:"column", gap:5 },
  lblT:      { fontSize:11, color:"#9a7060", fontWeight:700, letterSpacing:.5, textTransform:"uppercase" },
  inp:       { background:"#faf3ed", border:"1px solid #ecddd5", borderRadius:10, color:"#3a2418", padding:"12px 13px", fontSize:14, outline:"none", width:"100%", boxSizing:"border-box" },
};
